[[redirects]]
  from = "/order"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/reference"
  to = "/reference.html"
  status = 200

[[redirects]]
  from = "/admin"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings.html"
  status = 200