[[redirects]]
  from = "/"
  to = "/order.html"
  status = 200

[[redirects]]
  from = "/order"
  to = "/order.html"
  status = 200

[[redirects]]
  from = "/reference"
  to = "/reference.html"
  status = 200

[[redirects]]
  from = "/dashboard"
  to = "/dashboard.html"
  status = 200

[[redirects]]
  from = "/settings"
  to = "/settings.html"
  status = 200